#!/bin/bash
echo " creating init file 00_cellranger_submit.sh"
echo "#!/bin/bash" >> 00_cellranger_submit.sh
echo ""
echo "## link source scripts and resources"
echo "[[ -L src ]] || ln -s ../src/" >> 00_cellranger_submit.sh
echo "[[ -L res ]] || ln -s ../res/" >> 00_cellranger_submit.sh
## GRCh37: /work/singer/gularter/genomes/homo_sapiens/Ensembl/GRCh37.p13/Sequence/cellranger
echo "[[ -L hg38 ]] || ln -s /work/singer/genomes/homo_sapiens/Ensembl/GRCh38.p5/Sequence/refdata-gex-GRCh38-2020-A/ hg38"
echo ""
echo "## Generate preliminary files"
echo "[[ -d data-raw ]] | mkdir -p data-raw" >> 00_cellranger_submit.sh
echo "touch data-raw/DATASET.R" >> 00_cellranger_submit.sh
echo ""
echo ""
echo "## automatic generation of cellranger deployment commands"
echo '## for i in $( find seqdata/ | sort -V ) ; do echo "##" $( echo $i | sed "s:seqdata/Sample_::" | sed "s:_IGO.*::") ; echo "bsub -n 12 -R "rusage[mem=8]" -W 64:00 -R "span[hosts=1]" src/01_cellranger.sh" $( echo $i | sed "s:seqdata/Sample_::" | sed "s:_IGO.*::") $i $( echo $i | sed "s:seqdata/Sample_::") $( echo $i | sed "s:seqdata/Sample_::" | sed "s:_.*::" )  hg38"; echo "" ; done >> 00_cellranger_submit.sh' >> 00_cellranger_submit.sh



echo "" >> 00_cellranger_submit.sh
echo "" >> 00_cellranger_submit.sh
echo "## autogenerated commands to run: " >> 00_cellranger_submit.sh
echo "" >> 00_cellranger_submit.sh

chmod +x 00_cellranger_submit.sh
